// @ts-check

// 这在 Node.js 中运行 - 请不要在这里使用客户端代码（浏览器 API，JSX 等...）

/**
 * 创建侧边栏可以让你：
 - 创建一个有序的文档组
 - 为该组的每个文档渲染侧边栏
 - 提供前进/后退导航

 侧边栏可以从文件系统生成，也可以在此处显式定义。

 可以创建任意数量的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // 但你也可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
